# Automatically generated by configure - do not modify
include ../config-host.mak
TARGET_ARCH=ppc64
TARGET_ABI_DIR=ppc
TARGET_WORDS_BIGENDIAN=yes
CONFIG_SOFTMMU=yes
TARGET_XML_FILES= /usr/local/xen-4.4.0/tools/qemu-xen-traditional/gdb-xml/power64-core.xml /usr/local/xen-4.4.0/tools/qemu-xen-traditional/gdb-xml/power-fpu.xml /usr/local/xen-4.4.0/tools/qemu-xen-traditional/gdb-xml/power-altivec.xml /usr/local/xen-4.4.0/tools/qemu-xen-traditional/gdb-xml/power-spe.xml
CONFIG_SOFTFLOAT=yes
