# Automatically generated by configure - do not modify
include ../config-host.mak
TARGET_ARCH=arm
CONFIG_SOFTMMU=yes
TARGET_XML_FILES= /usr/local/xen-4.4.0/tools/qemu-xen-traditional/gdb-xml/arm-core.xml /usr/local/xen-4.4.0/tools/qemu-xen-traditional/gdb-xml/arm-vfp.xml /usr/local/xen-4.4.0/tools/qemu-xen-traditional/gdb-xml/arm-vfp3.xml /usr/local/xen-4.4.0/tools/qemu-xen-traditional/gdb-xml/arm-neon.xml
CONFIG_SOFTFLOAT=yes
