
/* DO NOT EDIT.
 *
 * This file is autogenerated by
 * "gentypes.py libxl_types_internal.idl __libxl_types_internal.h __libxl_types_internal_json.h __libxl_types_internal.c"
 */

#include "libxl_osdeps.h"

#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#include "libxl_internal.h"

#define LIBXL_DTOR_POISON 0xa5

void libxl__device_console_dispose(libxl__device_console *p)
{
    free(p->output);
    memset(p, LIBXL_DTOR_POISON, sizeof(*p));
}

void libxl__device_console_init(libxl__device_console *p)
{
    memset(p, '\0', sizeof(*p));
}

const char *libxl__qmp_message_type_to_string(libxl__qmp_message_type e)
{
    switch(e) {
        case LIBXL__QMP_MESSAGE_TYPE_QMP:
            return "qmp";
        case LIBXL__QMP_MESSAGE_TYPE_RETURN:
            return "return";
        case LIBXL__QMP_MESSAGE_TYPE_ERROR:
            return "error";
        case LIBXL__QMP_MESSAGE_TYPE_EVENT:
            return "event";
        case LIBXL__QMP_MESSAGE_TYPE_INVALID:
            return "invalid";
        default:
             return NULL;
    }
}

libxl_enum_string_table libxl__qmp_message_type_string_table[] = {
    { .s = "qmp", .v = LIBXL__QMP_MESSAGE_TYPE_QMP },
    { .s = "return", .v = LIBXL__QMP_MESSAGE_TYPE_RETURN },
    { .s = "error", .v = LIBXL__QMP_MESSAGE_TYPE_ERROR },
    { .s = "event", .v = LIBXL__QMP_MESSAGE_TYPE_EVENT },
    { .s = "invalid", .v = LIBXL__QMP_MESSAGE_TYPE_INVALID },
    { NULL, -1 },
};

int libxl__qmp_message_type_from_string(const char *s, libxl__qmp_message_type *e)
{
    return libxl__enum_from_string(libxl__qmp_message_type_string_table,
                                   s, (int *)e);
}

const char *libxl__device_kind_to_string(libxl__device_kind e)
{
    switch(e) {
        case LIBXL__DEVICE_KIND_VIF:
            return "vif";
        case LIBXL__DEVICE_KIND_VBD:
            return "vbd";
        case LIBXL__DEVICE_KIND_QDISK:
            return "qdisk";
        case LIBXL__DEVICE_KIND_PCI:
            return "pci";
        case LIBXL__DEVICE_KIND_VFB:
            return "vfb";
        case LIBXL__DEVICE_KIND_VKBD:
            return "vkbd";
        case LIBXL__DEVICE_KIND_CONSOLE:
            return "console";
        case LIBXL__DEVICE_KIND_VTPM:
            return "vtpm";
        default:
             return NULL;
    }
}

libxl_enum_string_table libxl__device_kind_string_table[] = {
    { .s = "vif", .v = LIBXL__DEVICE_KIND_VIF },
    { .s = "vbd", .v = LIBXL__DEVICE_KIND_VBD },
    { .s = "qdisk", .v = LIBXL__DEVICE_KIND_QDISK },
    { .s = "pci", .v = LIBXL__DEVICE_KIND_PCI },
    { .s = "vfb", .v = LIBXL__DEVICE_KIND_VFB },
    { .s = "vkbd", .v = LIBXL__DEVICE_KIND_VKBD },
    { .s = "console", .v = LIBXL__DEVICE_KIND_CONSOLE },
    { .s = "vtpm", .v = LIBXL__DEVICE_KIND_VTPM },
    { NULL, -1 },
};

int libxl__device_kind_from_string(const char *s, libxl__device_kind *e)
{
    return libxl__enum_from_string(libxl__device_kind_string_table,
                                   s, (int *)e);
}

const char *libxl__console_backend_to_string(libxl__console_backend e)
{
    switch(e) {
        case LIBXL__CONSOLE_BACKEND_XENCONSOLED:
            return "xenconsoled";
        case LIBXL__CONSOLE_BACKEND_IOEMU:
            return "ioemu";
        default:
             return NULL;
    }
}

libxl_enum_string_table libxl__console_backend_string_table[] = {
    { .s = "xenconsoled", .v = LIBXL__CONSOLE_BACKEND_XENCONSOLED },
    { .s = "ioemu", .v = LIBXL__CONSOLE_BACKEND_IOEMU },
    { NULL, -1 },
};

int libxl__console_backend_from_string(const char *s, libxl__console_backend *e)
{
    return libxl__enum_from_string(libxl__console_backend_string_table,
                                   s, (int *)e);
}

const char *libxl__device_action_to_string(libxl__device_action e)
{
    switch(e) {
        case LIBXL__DEVICE_ACTION_ADD:
            return "add";
        case LIBXL__DEVICE_ACTION_REMOVE:
            return "remove";
        default:
             return NULL;
    }
}

libxl_enum_string_table libxl__device_action_string_table[] = {
    { .s = "add", .v = LIBXL__DEVICE_ACTION_ADD },
    { .s = "remove", .v = LIBXL__DEVICE_ACTION_REMOVE },
    { NULL, -1 },
};

int libxl__device_action_from_string(const char *s, libxl__device_action *e)
{
    return libxl__enum_from_string(libxl__device_action_string_table,
                                   s, (int *)e);
}

yajl_gen_status libxl__qmp_message_type_gen_json(yajl_gen hand, libxl__qmp_message_type *p)
{
    yajl_gen_status s;
    s = libxl__yajl_gen_enum(hand, libxl__qmp_message_type_to_string(*p));
    if (s != yajl_gen_status_ok)
        goto out;
    out:
    return s;
}

char *libxl__qmp_message_type_to_json(libxl_ctx *ctx, libxl__qmp_message_type p)
{
    return libxl__object_to_json(ctx, "libxl__qmp_message_type", (libxl__gen_json_callback)&libxl__qmp_message_type_gen_json, (void *)&p);
}

yajl_gen_status libxl__device_kind_gen_json(yajl_gen hand, libxl__device_kind *p)
{
    yajl_gen_status s;
    s = libxl__yajl_gen_enum(hand, libxl__device_kind_to_string(*p));
    if (s != yajl_gen_status_ok)
        goto out;
    out:
    return s;
}

char *libxl__device_kind_to_json(libxl_ctx *ctx, libxl__device_kind p)
{
    return libxl__object_to_json(ctx, "libxl__device_kind", (libxl__gen_json_callback)&libxl__device_kind_gen_json, (void *)&p);
}

yajl_gen_status libxl__console_backend_gen_json(yajl_gen hand, libxl__console_backend *p)
{
    yajl_gen_status s;
    s = libxl__yajl_gen_enum(hand, libxl__console_backend_to_string(*p));
    if (s != yajl_gen_status_ok)
        goto out;
    out:
    return s;
}

char *libxl__console_backend_to_json(libxl_ctx *ctx, libxl__console_backend p)
{
    return libxl__object_to_json(ctx, "libxl__console_backend", (libxl__gen_json_callback)&libxl__console_backend_gen_json, (void *)&p);
}

yajl_gen_status libxl__device_console_gen_json(yajl_gen hand, libxl__device_console *p)
{
    yajl_gen_status s;
    s = yajl_gen_map_open(hand);
    if (s != yajl_gen_status_ok)
        goto out;
    s = yajl_gen_string(hand, (const unsigned char *)"backend_domid", sizeof("backend_domid")-1);
    if (s != yajl_gen_status_ok)
        goto out;
    s = yajl_gen_integer(hand, p->backend_domid);
    if (s != yajl_gen_status_ok)
        goto out;
    s = yajl_gen_string(hand, (const unsigned char *)"devid", sizeof("devid")-1);
    if (s != yajl_gen_status_ok)
        goto out;
    s = yajl_gen_integer(hand, p->devid);
    if (s != yajl_gen_status_ok)
        goto out;
    s = yajl_gen_string(hand, (const unsigned char *)"consback", sizeof("consback")-1);
    if (s != yajl_gen_status_ok)
        goto out;
    s = libxl__yajl_gen_enum(hand, libxl__console_backend_to_string(p->consback));
    if (s != yajl_gen_status_ok)
        goto out;
    s = yajl_gen_string(hand, (const unsigned char *)"output", sizeof("output")-1);
    if (s != yajl_gen_status_ok)
        goto out;
    s = libxl__string_gen_json(hand, p->output);
    if (s != yajl_gen_status_ok)
        goto out;
    s = yajl_gen_map_close(hand);
    if (s != yajl_gen_status_ok)
        goto out;
    out:
    return s;
}

char *libxl__device_console_to_json(libxl_ctx *ctx, libxl__device_console *p)
{
    return libxl__object_to_json(ctx, "libxl__device_console", (libxl__gen_json_callback)&libxl__device_console_gen_json, (void *)p);
}

yajl_gen_status libxl__device_action_gen_json(yajl_gen hand, libxl__device_action *p)
{
    yajl_gen_status s;
    s = libxl__yajl_gen_enum(hand, libxl__device_action_to_string(*p));
    if (s != yajl_gen_status_ok)
        goto out;
    out:
    return s;
}

char *libxl__device_action_to_json(libxl_ctx *ctx, libxl__device_action p)
{
    return libxl__object_to_json(ctx, "libxl__device_action", (libxl__gen_json_callback)&libxl__device_action_gen_json, (void *)&p);
}

