#ifndef __PYXL_TYPES_H
#define __PYXL_TYPES_H

/*
 * DO NOT EDIT.
 *
 * This file is autogenerated by
 * "genwrap.py /usr/local/xen-4.4.0/tools/python/../../tools/libxl/libxl_types.idl xen/lowlevel/xl/_pyxl_types.h xen/lowlevel/xl/_pyxl_types.c"
 */

#define PKG "xen.lowlevel.xl"

#if __GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 1)
#define _hidden __attribute__((visibility("hidden")))
#define _protected __attribute__((visibility("protected")))
#else
#define _hidden
#define _protected
#endif

/* Initialise all types */
_hidden void genwrap__init(PyObject *m);

/* Generic type initialiser */
_hidden int genwrap__obj_init(PyObject *self, PyObject *args, PyObject *kwds);

/* Auto-generated get/set functions for simple data-types */
_hidden int genwrap__string_set(PyObject *v, char **str);
_hidden PyObject *genwrap__string_get(char **str);
_hidden PyObject *genwrap__ull_get(unsigned long long val);
_hidden int genwrap__ull_set(PyObject *v, unsigned long long *val, unsigned long long mask);
_hidden PyObject *genwrap__ll_get(long long val);
_hidden int genwrap__ll_set(PyObject *v, long long *val, long long mask);
_hidden PyObject *genwrap__defbool_get(libxl_defbool *db);
_hidden int genwrap__defbool_set(PyObject *v, libxl_defbool *db);

/* Internal API for libxl_ioport_range wrapper */
typedef struct {
    PyObject_HEAD;
    libxl_ioport_range obj;
}Py_ioport_range;

_hidden Py_ioport_range *Pyioport_range_New(void);

_hidden int Pyioport_range_Check(PyObject *self);


/* Internal API for libxl_iomem_range wrapper */
typedef struct {
    PyObject_HEAD;
    libxl_iomem_range obj;
}Py_iomem_range;

_hidden Py_iomem_range *Pyiomem_range_New(void);

_hidden int Pyiomem_range_Check(PyObject *self);


/* Internal API for libxl_vga_interface_info wrapper */
typedef struct {
    PyObject_HEAD;
    libxl_vga_interface_info obj;
}Py_vga_interface_info;

_hidden Py_vga_interface_info *Pyvga_interface_info_New(void);

_hidden int Pyvga_interface_info_Check(PyObject *self);


/* Internal API for libxl_vnc_info wrapper */
typedef struct {
    PyObject_HEAD;
    libxl_vnc_info obj;
}Py_vnc_info;

_hidden Py_vnc_info *Pyvnc_info_New(void);

_hidden int Pyvnc_info_Check(PyObject *self);


/* Internal API for libxl_spice_info wrapper */
typedef struct {
    PyObject_HEAD;
    libxl_spice_info obj;
}Py_spice_info;

_hidden Py_spice_info *Pyspice_info_New(void);

_hidden int Pyspice_info_Check(PyObject *self);


/* Internal API for libxl_sdl_info wrapper */
typedef struct {
    PyObject_HEAD;
    libxl_sdl_info obj;
}Py_sdl_info;

_hidden Py_sdl_info *Pysdl_info_New(void);

_hidden int Pysdl_info_Check(PyObject *self);


/* Internal API for libxl_dominfo wrapper */
typedef struct {
    PyObject_HEAD;
    libxl_dominfo obj;
}Py_dominfo;

_hidden Py_dominfo *Pydominfo_New(void);

_hidden int Pydominfo_Check(PyObject *self);

_hidden PyObject *attrib__libxl_uuid_get(libxl_uuid *uuid);
_hidden PyObject *attrib__libxl_domid_get(libxl_domid *domid);

/* Internal API for libxl_cpupoolinfo wrapper */
typedef struct {
    PyObject_HEAD;
    libxl_cpupoolinfo obj;
}Py_cpupoolinfo;

_hidden Py_cpupoolinfo *Pycpupoolinfo_New(void);

_hidden int Pycpupoolinfo_Check(PyObject *self);

_hidden PyObject *attrib__libxl_bitmap_get(libxl_bitmap *cpumap);

/* Internal API for libxl_vminfo wrapper */
typedef struct {
    PyObject_HEAD;
    libxl_vminfo obj;
}Py_vminfo;

_hidden Py_vminfo *Pyvminfo_New(void);

_hidden int Pyvminfo_Check(PyObject *self);

_hidden PyObject *attrib__libxl_uuid_get(libxl_uuid *uuid);
_hidden PyObject *attrib__libxl_domid_get(libxl_domid *domid);

/* Internal API for libxl_version_info wrapper */
typedef struct {
    PyObject_HEAD;
    libxl_version_info obj;
}Py_version_info;

_hidden Py_version_info *Pyversion_info_New(void);

_hidden int Pyversion_info_Check(PyObject *self);


/* Internal API for libxl_domain_create_info wrapper */
typedef struct {
    PyObject_HEAD;
    libxl_domain_create_info obj;
}Py_domain_create_info;

_hidden Py_domain_create_info *Pydomain_create_info_New(void);

_hidden int Pydomain_create_info_Check(PyObject *self);

_hidden int attrib__libxl_uuid_set(PyObject *v, libxl_uuid *uuid);
_hidden int attrib__libxl_key_value_list_set(PyObject *v, libxl_key_value_list *xsdata);
_hidden int attrib__libxl_key_value_list_set(PyObject *v, libxl_key_value_list *platformdata);

/* Internal API for libxl_domain_restore_params wrapper */
typedef struct {
    PyObject_HEAD;
    libxl_domain_restore_params obj;
}Py_domain_restore_params;

_hidden Py_domain_restore_params *Pydomain_restore_params_New(void);

_hidden int Pydomain_restore_params_Check(PyObject *self);


/* Internal API for libxl_domain_sched_params wrapper */
typedef struct {
    PyObject_HEAD;
    libxl_domain_sched_params obj;
}Py_domain_sched_params;

_hidden Py_domain_sched_params *Pydomain_sched_params_New(void);

_hidden int Pydomain_sched_params_Check(PyObject *self);


/* Internal API for libxl_domain_build_info wrapper */
typedef struct {
    PyObject_HEAD;
    libxl_domain_build_info obj;
}Py_domain_build_info;

_hidden Py_domain_build_info *Pydomain_build_info_New(void);

_hidden int Pydomain_build_info_Check(PyObject *self);

_hidden int attrib__libxl_bitmap_set(PyObject *v, libxl_bitmap *avail_vcpus);
_hidden int attrib__libxl_bitmap_set(PyObject *v, libxl_bitmap *cpumap);
_hidden int attrib__libxl_bitmap_set(PyObject *v, libxl_bitmap *nodemap);
_hidden int attrib__libxl_cpuid_policy_list_set(PyObject *v, libxl_cpuid_policy_list *cpuid);
_hidden int attrib__libxl_string_list_set(PyObject *v, libxl_string_list *extra);
_hidden int attrib__libxl_string_list_set(PyObject *v, libxl_string_list *extra_pv);
_hidden int attrib__libxl_string_list_set(PyObject *v, libxl_string_list *extra_hvm);

/* Internal API for libxl_device_vfb wrapper */
typedef struct {
    PyObject_HEAD;
    libxl_device_vfb obj;
}Py_device_vfb;

_hidden Py_device_vfb *Pydevice_vfb_New(void);

_hidden int Pydevice_vfb_Check(PyObject *self);

_hidden PyObject *attrib__libxl_domid_get(libxl_domid *backend_domid);
_hidden int attrib__libxl_domid_set(PyObject *v, libxl_domid *backend_domid);
_hidden PyObject *attrib__libxl_devid_get(libxl_devid *devid);
_hidden int attrib__libxl_devid_set(PyObject *v, libxl_devid *devid);

/* Internal API for libxl_device_vkb wrapper */
typedef struct {
    PyObject_HEAD;
    libxl_device_vkb obj;
}Py_device_vkb;

_hidden Py_device_vkb *Pydevice_vkb_New(void);

_hidden int Pydevice_vkb_Check(PyObject *self);

_hidden PyObject *attrib__libxl_domid_get(libxl_domid *backend_domid);
_hidden int attrib__libxl_domid_set(PyObject *v, libxl_domid *backend_domid);
_hidden PyObject *attrib__libxl_devid_get(libxl_devid *devid);
_hidden int attrib__libxl_devid_set(PyObject *v, libxl_devid *devid);

/* Internal API for libxl_device_disk wrapper */
typedef struct {
    PyObject_HEAD;
    libxl_device_disk obj;
}Py_device_disk;

_hidden Py_device_disk *Pydevice_disk_New(void);

_hidden int Pydevice_disk_Check(PyObject *self);

_hidden PyObject *attrib__libxl_domid_get(libxl_domid *backend_domid);
_hidden int attrib__libxl_domid_set(PyObject *v, libxl_domid *backend_domid);

/* Internal API for libxl_device_nic wrapper */
typedef struct {
    PyObject_HEAD;
    libxl_device_nic obj;
}Py_device_nic;

_hidden Py_device_nic *Pydevice_nic_New(void);

_hidden int Pydevice_nic_Check(PyObject *self);

_hidden PyObject *attrib__libxl_domid_get(libxl_domid *backend_domid);
_hidden int attrib__libxl_domid_set(PyObject *v, libxl_domid *backend_domid);
_hidden PyObject *attrib__libxl_devid_get(libxl_devid *devid);
_hidden int attrib__libxl_devid_set(PyObject *v, libxl_devid *devid);
_hidden PyObject *attrib__libxl_mac_get(libxl_mac *mac);
_hidden int attrib__libxl_mac_set(PyObject *v, libxl_mac *mac);

/* Internal API for libxl_device_pci wrapper */
typedef struct {
    PyObject_HEAD;
    libxl_device_pci obj;
}Py_device_pci;

_hidden Py_device_pci *Pydevice_pci_New(void);

_hidden int Pydevice_pci_Check(PyObject *self);


/* Internal API for libxl_device_vtpm wrapper */
typedef struct {
    PyObject_HEAD;
    libxl_device_vtpm obj;
}Py_device_vtpm;

_hidden Py_device_vtpm *Pydevice_vtpm_New(void);

_hidden int Pydevice_vtpm_Check(PyObject *self);

_hidden PyObject *attrib__libxl_domid_get(libxl_domid *backend_domid);
_hidden int attrib__libxl_domid_set(PyObject *v, libxl_domid *backend_domid);
_hidden PyObject *attrib__libxl_devid_get(libxl_devid *devid);
_hidden int attrib__libxl_devid_set(PyObject *v, libxl_devid *devid);
_hidden PyObject *attrib__libxl_uuid_get(libxl_uuid *uuid);
_hidden int attrib__libxl_uuid_set(PyObject *v, libxl_uuid *uuid);

/* Internal API for libxl_domain_config wrapper */
typedef struct {
    PyObject_HEAD;
    libxl_domain_config obj;
}Py_domain_config;

_hidden Py_domain_config *Pydomain_config_New(void);

_hidden int Pydomain_config_Check(PyObject *self);


/* Internal API for libxl_diskinfo wrapper */
typedef struct {
    PyObject_HEAD;
    libxl_diskinfo obj;
}Py_diskinfo;

_hidden Py_diskinfo *Pydiskinfo_New(void);

_hidden int Pydiskinfo_Check(PyObject *self);

_hidden PyObject *attrib__libxl_devid_get(libxl_devid *devid);

/* Internal API for libxl_nicinfo wrapper */
typedef struct {
    PyObject_HEAD;
    libxl_nicinfo obj;
}Py_nicinfo;

_hidden Py_nicinfo *Pynicinfo_New(void);

_hidden int Pynicinfo_Check(PyObject *self);

_hidden PyObject *attrib__libxl_devid_get(libxl_devid *devid);

/* Internal API for libxl_vtpminfo wrapper */
typedef struct {
    PyObject_HEAD;
    libxl_vtpminfo obj;
}Py_vtpminfo;

_hidden Py_vtpminfo *Pyvtpminfo_New(void);

_hidden int Pyvtpminfo_Check(PyObject *self);

_hidden PyObject *attrib__libxl_devid_get(libxl_devid *devid);
_hidden PyObject *attrib__libxl_uuid_get(libxl_uuid *uuid);

/* Internal API for libxl_vcpuinfo wrapper */
typedef struct {
    PyObject_HEAD;
    libxl_vcpuinfo obj;
}Py_vcpuinfo;

_hidden Py_vcpuinfo *Pyvcpuinfo_New(void);

_hidden int Pyvcpuinfo_Check(PyObject *self);

_hidden PyObject *attrib__libxl_bitmap_get(libxl_bitmap *cpumap);

/* Internal API for libxl_physinfo wrapper */
typedef struct {
    PyObject_HEAD;
    libxl_physinfo obj;
}Py_physinfo;

_hidden Py_physinfo *Pyphysinfo_New(void);

_hidden int Pyphysinfo_Check(PyObject *self);

_hidden PyObject *attrib__libxl_hwcap_get(libxl_hwcap *hw_cap);

/* Internal API for libxl_numainfo wrapper */
typedef struct {
    PyObject_HEAD;
    libxl_numainfo obj;
}Py_numainfo;

_hidden Py_numainfo *Pynumainfo_New(void);

_hidden int Pynumainfo_Check(PyObject *self);


/* Internal API for libxl_cputopology wrapper */
typedef struct {
    PyObject_HEAD;
    libxl_cputopology obj;
}Py_cputopology;

_hidden Py_cputopology *Pycputopology_New(void);

_hidden int Pycputopology_Check(PyObject *self);


/* Internal API for libxl_sched_credit_params wrapper */
typedef struct {
    PyObject_HEAD;
    libxl_sched_credit_params obj;
}Py_sched_credit_params;

_hidden Py_sched_credit_params *Pysched_credit_params_New(void);

_hidden int Pysched_credit_params_Check(PyObject *self);


/* Internal API for libxl_domain_remus_info wrapper */
typedef struct {
    PyObject_HEAD;
    libxl_domain_remus_info obj;
}Py_domain_remus_info;

_hidden Py_domain_remus_info *Pydomain_remus_info_New(void);

_hidden int Pydomain_remus_info_Check(PyObject *self);


/* Internal API for libxl_event wrapper */
typedef struct {
    PyObject_HEAD;
    libxl_event obj;
}Py_event;

_hidden Py_event *Pyevent_New(void);

_hidden int Pyevent_Check(PyObject *self);

_hidden PyObject *attrib__libxl_ev_link_get(libxl_ev_link *link);
_hidden int attrib__libxl_ev_link_set(PyObject *v, libxl_ev_link *link);
_hidden PyObject *attrib__libxl_domid_get(libxl_domid *domid);
_hidden int attrib__libxl_domid_set(PyObject *v, libxl_domid *domid);
_hidden PyObject *attrib__libxl_uuid_get(libxl_uuid *domuuid);
_hidden int attrib__libxl_uuid_set(PyObject *v, libxl_uuid *domuuid);

#endif /* __PYXL_TYPES_H */
